.TH "/home/chris/Taller2Match/ApplicationServer/src/HandlersHTTP Directory Reference" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/chris/Taller2Match/ApplicationServer/src/HandlersHTTP Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBChatHTTP\&.cpp\fP"
.br
.ti -1c
.RI "file \fBChatHTTP\&.h\fP"
.br
.ti -1c
.RI "file \fBMatcherHTTP\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMatcherHTTP\&.h\fP"
.br
.ti -1c
.RI "file \fBMatchRequestHandler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMatchRequestHandler\&.h\fP"
.br
.ti -1c
.RI "file \fBNotifier\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNotifier\&.h\fP"
.br
.ti -1c
.RI "file \fBRequestHandler\&.h\fP"
.br
.ti -1c
.RI "file \fBUsersHTTP\&.cpp\fP"
.br
.ti -1c
.RI "file \fBUsersHTTP\&.h\fP"
.br
.in -1c
