.TH "/home/chris/Taller2Match/ApplicationServer/src Directory Reference" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/chris/Taller2Match/ApplicationServer/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBDB\fP"
.br
.ti -1c
.RI "directory \fBHandlers\fP"
.br
.ti -1c
.RI "directory \fBHandlersHTTP\fP"
.br
.ti -1c
.RI "directory \fBHTTP\fP"
.br
.ti -1c
.RI "directory \fBMongoose\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDate\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDate\&.h\fP"
.br
.ti -1c
.RI "file \fBInterest\&.cpp\fP"
.br
.ti -1c
.RI "file \fBInterest\&.h\fP"
.br
.ti -1c
.RI "file \fBlogger\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogger\&.h\fP"
.br
.ti -1c
.RI "file \fBSharedData\&.h\fP"
.br
.ti -1c
.RI "file \fBSharedServerConnection\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSharedServerConnection\&.h\fP"
.br
.ti -1c
.RI "file \fBUserProfile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBUserProfile\&.h\fP"
.br
.ti -1c
.RI "file \fBUsersProfiles\&.cpp\fP"
.br
.ti -1c
.RI "file \fBUsersProfiles\&.h\fP"
.br
.ti -1c
.RI "file \fButil\&.cpp\fP"
.br
.ti -1c
.RI "file \fButil\&.h\fP"
.br
.in -1c
