.TH "cs_sha1_ctx" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cs_sha1_ctx \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBstate\fP [5]"
.br
.ti -1c
.RI "uint32_t \fBcount\fP [2]"
.br
.ti -1c
.RI "unsigned char \fBbuffer\fP [64]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
