.TH "ctl_msg" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctl_msg \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "mg_event_handler_t \fBcallback\fP"
.br
.ti -1c
.RI "char \fBmessage\fP [MG_CTL_MSG_MESSAGE_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
