.TH "Date" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Date \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDate\fP (std::string str)"
.br
.ti -1c
.RI "\fBDate\fP (int day, int month, int year)"
.br
.ti -1c
.RI "std::string \fBstr\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDate\fP \fBtoday\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBDate\fP &lhs, const \fBDate\fP &rhs)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
