.TH "http_message" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
http_message \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBmg_str\fP \fBmessage\fP"
.br
.ti -1c
.RI "struct \fBmg_str\fP \fBmethod\fP"
.br
.ti -1c
.RI "struct \fBmg_str\fP \fBuri\fP"
.br
.ti -1c
.RI "struct \fBmg_str\fP \fBproto\fP"
.br
.ti -1c
.RI "int \fBresp_code\fP"
.br
.ti -1c
.RI "struct \fBmg_str\fP \fBresp_status_msg\fP"
.br
.ti -1c
.RI "struct \fBmg_str\fP \fBquery_string\fP"
.br
.ti -1c
.RI "struct \fBmg_str\fP \fBheader_names\fP [MG_MAX_HTTP_HEADERS]"
.br
.ti -1c
.RI "struct \fBmg_str\fP \fBheader_values\fP [MG_MAX_HTTP_HEADERS]"
.br
.ti -1c
.RI "struct \fBmg_str\fP \fBbody\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
