.TH "Json::PathArgument" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::PathArgument \- 
.PP
Experimental and untested: represents an element of the 'path' to access a node\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPathArgument\fP (ArrayIndex index)"
.br
.ti -1c
.RI "\fBPathArgument\fP (const char *key)"
.br
.ti -1c
.RI "\fBPathArgument\fP (const JSONCPP_STRING &key)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBPath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Experimental and untested: represents an element of the 'path' to access a node\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
