.TH "MatcherHTTP" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatcherHTTP \- 
.PP
Esta clase maneja los request HTTP que tienen que ver con los likes, matches, etc\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatcherHTTP\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatcherHTTP\fP (\fBUsers\fP &users, \fBMatcher\fP &matcher)"
.br
.ti -1c
.RI "\fBHTTPResponse\fP \fBhandle\fP (\fBHTTPRequest\fP request)"
.br
.ti -1c
.RI "\fBHTTPResponse\fP \fBhandleGetMatches\fP (\fBHTTPRequest\fP &request)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Esta clase maneja los request HTTP que tienen que ver con los likes, matches, etc\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
