.TH "mg_cgi_env_block" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mg_cgi_env_block \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBmg_connection\fP * \fBnc\fP"
.br
.ti -1c
.RI "char \fBbuf\fP [MG_CGI_ENVIRONMENT_SIZE]"
.br
.ti -1c
.RI "const char * \fBvars\fP [MG_MAX_CGI_ENVIR_VARS]"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "int \fBnvars\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
