.TH "mg_http_proto_data_file" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mg_http_proto_data_file \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBfp\fP"
.br
.ti -1c
.RI "int64_t \fBcl\fP"
.br
.ti -1c
.RI "int64_t \fBsent\fP"
.br
.ti -1c
.RI "enum mg_http_proto_data_type \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
