.TH "mg_mgr" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mg_mgr \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBmg_connection\fP * \fBactive_connections\fP"
.br
.ti -1c
.RI "const char * \fBhexdump_file\fP"
.br
.ti -1c
.RI "sock_t \fBctl\fP [2]"
.br
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.ti -1c
.RI "void * \fBmgr_data\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
