.TH "mg_mqtt_message" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mg_mqtt_message \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcmd\fP"
.br
.ti -1c
.RI "struct \fBmg_str\fP \fBpayload\fP"
.br
.ti -1c
.RI "int \fBqos\fP"
.br
.ti -1c
.RI "uint8_t \fBconnack_ret_code\fP"
.br
.ti -1c
.RI "uint16_t \fBmessage_id\fP"
.br
.ti -1c
.RI "char * \fBtopic\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
