.TH "mg_rpc_error" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mg_rpc_error \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjson_token\fP * \fBmessage\fP"
.br
.ti -1c
.RI "struct \fBjson_token\fP * \fBid\fP"
.br
.ti -1c
.RI "struct \fBjson_token\fP * \fBerror_code\fP"
.br
.ti -1c
.RI "struct \fBjson_token\fP * \fBerror_message\fP"
.br
.ti -1c
.RI "struct \fBjson_token\fP * \fBerror_data\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
