.TH "mg_resolve_async_opts" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mg_resolve_async_opts \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBnameserver_url\fP"
.br
.ti -1c
.RI "int \fBmax_retries\fP"
.br
.ti -1c
.RI "int \fBtimeout\fP"
.br
.ti -1c
.RI "int \fBaccept_literal\fP"
.br
.ti -1c
.RI "int \fBonly_literal\fP"
.br
.ti -1c
.RI "struct \fBmg_connection\fP ** \fBdns_conn\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
