.TH "mg_serve_http_opts" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mg_serve_http_opts \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBdocument_root\fP"
.br
.ti -1c
.RI "const char * \fBindex_files\fP"
.br
.ti -1c
.RI "const char * \fBper_directory_auth_file\fP"
.br
.ti -1c
.RI "const char * \fBauth_domain\fP"
.br
.ti -1c
.RI "const char * \fBglobal_auth_file\fP"
.br
.ti -1c
.RI "const char * \fBenable_directory_listing\fP"
.br
.ti -1c
.RI "const char * \fBssi_pattern\fP"
.br
.ti -1c
.RI "const char * \fBip_acl\fP"
.br
.ti -1c
.RI "const char * \fBurl_rewrites\fP"
.br
.ti -1c
.RI "const char * \fBdav_document_root\fP"
.br
.ti -1c
.RI "const char * \fBdav_auth_file\fP"
.br
.ti -1c
.RI "const char * \fBhidden_file_pattern\fP"
.br
.ti -1c
.RI "const char * \fBcgi_file_pattern\fP"
.br
.ti -1c
.RI "const char * \fBcgi_interpreter\fP"
.br
.ti -1c
.RI "const char * \fBcustom_mime_types\fP"
.br
.ti -1c
.RI "const char * \fBextra_headers\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
