.TH "mg_send_mqtt_handshake_opts" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mg_send_mqtt_handshake_opts \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBflags\fP"
.br
.ti -1c
.RI "uint16_t \fBkeep_alive\fP"
.br
.ti -1c
.RI "const char * \fBwill_topic\fP"
.br
.ti -1c
.RI "const char * \fBwill_message\fP"
.br
.ti -1c
.RI "const char * \fBuser_name\fP"
.br
.ti -1c
.RI "const char * \fBpassword\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
