.TH "MgConnectionManager" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MgConnectionManager \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "mg_connection * \fBconfigureListeningConnection\fP (std::string port, void *data, mg_event_handler_t eventHandler)"
.br
.ti -1c
.RI "void \fBpoll\fP (int everyMilliseconds)"
.br
.ti -1c
.RI "mg_connection * \fBconfigureOutboundConnection\fP (std::string url, void *data, mg_event_handler_t eventHandler)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
