.TH "MgServer" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MgServer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstart\fP ()"
.br
.RI "\fIInicia el server\&. \fP"
.ti -1c
.RI "void \fBstop\fP ()"
.br
.RI "\fIDetiene el server\&. \fP"
.ti -1c
.RI "\fBMgServer\fP (std::string port, \fBRequestHandler\fP &handlerSelector)"
.br
.RI "\fICrea el server con un port donde escucha conexiones entrantes, y una URL (URL:port) del Shared \fBMgServer\fP\&. \fP"
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
