.TH "ProfilesDatabase" 3 "Fri May 27 2016" "Match - Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProfilesDatabase \-
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetShared\fP (\fBSharedData\fP &sharedData)"
.br
.ti -1c
.RI "string \fBgetUserId\fP (string email)"
.br
.ti -1c
.RI "bool \fBgetProfile\fP (string userId, \fBUserProfile\fP *userProfile)"
.br
.ti -1c
.RI "bool \fBnewUser\fP (\fBUserProfile\fP userProfile, string *userId)"
.br
.ti -1c
.RI "bool \fBgetUsers\fP (map< string, \fBUserProfile\fP > *users)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Match - Application Server from the source code\&.
